"""initial schema

Revision ID: ea3cbfce14c6
Revises: 
Create Date: 2026-07-11 11:17:56.845519
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # ensure Text is available for JSONB(astext_type=Text()) renders
from sqlalchemy.dialects import postgresql

revision: str = 'ea3cbfce14c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_products',
    sa.Column('code', sa.Enum('MAIN_BANNER', 'SUB_BANNER', 'CATEGORY_AD', 'SPLASH', name='adproductcode', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('definition', sa.String(length=500), nullable=True),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('fit_purposes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('base_price_band', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('behavior_aggregates',
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('dimension', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('wish_count', sa.Integer(), nullable=True),
    sa.Column('cart_count', sa.Integer(), nullable=True),
    sa.Column('search_count', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.Enum('MAJOR', 'MIDDLE', 'MINOR', name='categorylevel', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)

    op.create_table('customer_segments',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_aggregates',
    sa.Column('dimension', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('resource', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_permission_code')
    )
    op.create_table('prompts',
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_aggregates',
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('dimension', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('purchase_count', sa.Integer(), nullable=True),
    sa.Column('reservation_count', sa.Integer(), nullable=True),
    sa.Column('avg_order_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('repurchase_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('cancel_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ad_product_category_rules',
    sa.Column('ad_product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('condition', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('boost_factor', sa.String(length=20), nullable=False),
    sa.Column('boost_points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ad_product_id'], ['ad_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_product_category_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_product_category_rules_ad_product_id'), ['ad_product_id'], unique=False)

    op.create_table('advertisers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('primary_category_id', sa.Uuid(), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('size', sa.String(length=60), nullable=True),
    sa.Column('budget_band', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Enum('CANDIDATE', 'IN_REVIEW', 'PROPOSED', 'CONTRACTED', 'ARCHIVED', name='advertiserstatus', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('DISCOVERY', 'MANUAL', name='advertisersource', native_enum=False), nullable=False),
    sa.Column('profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['primary_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advertisers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_advertisers_primary_category_id'), ['primary_category_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('benchmarks',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('ad_product_code', sa.Enum('MAIN_BANNER', 'SUB_BANNER', 'CATEGORY_AD', 'SPLASH', name='adproductcode', native_enum=False), nullable=False),
    sa.Column('avg_ctr', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('avg_cvr', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('avg_cpm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_order_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('industry_avg_roi', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('benchmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmarks_category_id'), ['category_id'], unique=False)

    op.create_table('competitors',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('type', sa.Enum('DIRECT', 'INDIRECT', 'LEADER', 'MEDIA', 'COMMERCE', 'OTA', 'CONTENT', 'LOCAL', name='competitortype', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitors_category_id'), ['category_id'], unique=False)

    op.create_table('market_research',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('market_size', sa.String(length=255), nullable=True),
    sa.Column('growth_rate', sa.String(length=120), nullable=True),
    sa.Column('trends', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('consumer_traits', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('opportunities', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('risks', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_research', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_research_category_id'), ['category_id'], unique=False)

    op.create_table('prompt_versions',
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('input_variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('output_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='promptstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_prompt_id'), ['prompt_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('scoring_versions',
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='scoringversionstatus', native_enum=False), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('ad_product_recommendations',
    sa.Column('advertiser_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=120), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('combo', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('target_audience', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('creative_direction', sa.String(length=1000), nullable=True),
    sa.Column('risks', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_product_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_product_recommendations_advertiser_id'), ['advertiser_id'], unique=False)

    op.create_table('advertiser_categories',
    sa.Column('advertiser_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('advertiser_id', 'category_id')
    )
    op.create_table('advertiser_scores',
    sa.Column('advertiser_id', sa.Uuid(), nullable=False),
    sa.Column('scoring_version_id', sa.Uuid(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('grade', sa.Enum('S', 'A', 'B', 'C', 'D', name='grade', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scoring_version_id'], ['scoring_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advertiser_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advertiser_scores_advertiser_id'), ['advertiser_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advertiser_scores_scoring_version_id'), ['scoring_version_id'], unique=False)

    op.create_table('agent_executions',
    sa.Column('agent', sa.Enum('CATEGORY_CLASSIFICATION', 'MARKET_RESEARCH', 'COMPETITOR_DISCOVERY', 'COMPETITOR_INTELLIGENCE', 'ADVERTISER_DISCOVERY', 'ADVERTISER_SCORING', 'AD_PRODUCT_RECOMMENDATION', 'PROPOSAL', 'PERFORMANCE_ANALYSIS', 'ROI', 'RENEWAL', name='agentname', native_enum=False), nullable=False),
    sa.Column('prompt_version_id', sa.Uuid(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('input_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='executionstatus', native_enum=False), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('advertiser_id', sa.Uuid(), nullable=False),
    sa.Column('ad_product_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.String(length=20), nullable=True),
    sa.Column('period_end', sa.String(length=20), nullable=True),
    sa.Column('contract_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'RUNNING', 'PAUSED', 'ENDED', name='campaignstatus', native_enum=False), nullable=False),
    sa.Column('creatives', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ad_product_id'], ['ad_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_ad_product_id'), ['ad_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_advertiser_id'), ['advertiser_id'], unique=False)

    op.create_table('competitor_analyses',
    sa.Column('competitor_id', sa.Uuid(), nullable=False),
    sa.Column('products', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('pricing', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('promotion', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('channels', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('strengths', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('weaknesses', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('differentiators', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('competition_intensity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitor_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_analyses_competitor_id'), ['competitor_id'], unique=True)

    op.create_table('proposals',
    sa.Column('advertiser_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'SENT', 'ACCEPTED', 'REJECTED', name='proposalstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposals_advertiser_id'), ['advertiser_id'], unique=False)

    op.create_table('score_factor_defs',
    sa.Column('scoring_version_id', sa.Uuid(), nullable=False),
    sa.Column('target', sa.String(length=30), nullable=False),
    sa.Column('factor_code', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('calc_method', sa.Enum('LINEAR', 'THRESHOLD', 'LOOKUP', 'AGG_RATIO', name='calcmethod', native_enum=False), nullable=False),
    sa.Column('category_scope', sa.String(length=120), nullable=True),
    sa.Column('indicators', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scoring_version_id'], ['scoring_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_factor_defs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_factor_defs_scoring_version_id'), ['scoring_version_id'], unique=False)

    op.create_table('ad_product_rec_items',
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('ad_product_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('fit_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('est_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ad_product_id'], ['ad_products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['ad_product_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_product_rec_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_product_rec_items_ad_product_id'), ['ad_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_product_rec_items_recommendation_id'), ['recommendation_id'], unique=False)

    op.create_table('ai_analysis_sources',
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('ref_type', sa.String(length=60), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_fact', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['competitor_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analysis_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analysis_sources_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('campaign_performances',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('cvr', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('roas', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('roi', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('analysis', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_performances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_performances_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('proposal_versions',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('export_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposal_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_versions_proposal_id'), ['proposal_id'], unique=False)

    op.create_table('renewal_recommendations',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('likelihood', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='renewallikelihood', native_enum=False), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('rationale', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('renewal_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_renewal_recommendations_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('score_factors',
    sa.Column('advertiser_score_id', sa.Uuid(), nullable=False),
    sa.Column('factor_code', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.String(length=1000), nullable=True),
    sa.Column('data_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_inference', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_score_id'], ['advertiser_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_factors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_factors_advertiser_score_id'), ['advertiser_score_id'], unique=False)

    op.create_table('upsell_recommendations',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('target_ad_product_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_ad_product_id'], ['ad_products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upsell_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upsell_recommendations_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upsell_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upsell_recommendations_campaign_id'))

    op.drop_table('upsell_recommendations')
    with op.batch_alter_table('score_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_factors_advertiser_score_id'))

    op.drop_table('score_factors')
    with op.batch_alter_table('renewal_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_renewal_recommendations_campaign_id'))

    op.drop_table('renewal_recommendations')
    with op.batch_alter_table('proposal_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_versions_proposal_id'))

    op.drop_table('proposal_versions')
    with op.batch_alter_table('campaign_performances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_performances_campaign_id'))

    op.drop_table('campaign_performances')
    with op.batch_alter_table('ai_analysis_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analysis_sources_analysis_id'))

    op.drop_table('ai_analysis_sources')
    with op.batch_alter_table('ad_product_rec_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_product_rec_items_recommendation_id'))
        batch_op.drop_index(batch_op.f('ix_ad_product_rec_items_ad_product_id'))

    op.drop_table('ad_product_rec_items')
    with op.batch_alter_table('score_factor_defs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_factor_defs_scoring_version_id'))

    op.drop_table('score_factor_defs')
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposals_advertiser_id'))

    op.drop_table('proposals')
    with op.batch_alter_table('competitor_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_analyses_competitor_id'))

    op.drop_table('competitor_analyses')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_advertiser_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_ad_product_id'))

    op.drop_table('campaigns')
    op.drop_table('agent_executions')
    with op.batch_alter_table('advertiser_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advertiser_scores_scoring_version_id'))
        batch_op.drop_index(batch_op.f('ix_advertiser_scores_advertiser_id'))

    op.drop_table('advertiser_scores')
    op.drop_table('advertiser_categories')
    with op.batch_alter_table('ad_product_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_product_recommendations_advertiser_id'))

    op.drop_table('ad_product_recommendations')
    op.drop_table('user_roles')
    op.drop_table('scoring_versions')
    op.drop_table('role_permissions')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_prompt_id'))

    op.drop_table('prompt_versions')
    with op.batch_alter_table('market_research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_research_category_id'))

    op.drop_table('market_research')
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitors_category_id'))

    op.drop_table('competitors')
    with op.batch_alter_table('benchmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmarks_category_id'))

    op.drop_table('benchmarks')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advertisers_primary_category_id'))
        batch_op.drop_index(batch_op.f('ix_advertisers_name'))

    op.drop_table('advertisers')
    with op.batch_alter_table('ad_product_category_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_product_category_rules_ad_product_id'))

    op.drop_table('ad_product_category_rules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('purchase_aggregates')
    op.drop_table('prompts')
    op.drop_table('permissions')
    op.drop_table('member_aggregates')
    op.drop_table('customer_segments')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))

    op.drop_table('categories')
    op.drop_table('behavior_aggregates')
    op.drop_table('ad_products')
    # ### end Alembic commands ###
